#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE_ROOTS = [ROOT / "csharp/src/BiliSubStudio.Core", ROOT / "csharp/src/BiliSubStudio.App"]
OUTPUT = ROOT / "docs/migration/CSHARP_CODE_MAP.generated.md"

TYPE_RE = re.compile(r"\b(?:public|internal|private|protected)?\s*(?:sealed\s+|static\s+|partial\s+|abstract\s+)*(?:class|record|struct|interface|enum)\s+([A-Za-z_]\w*)")
METHOD_RE = re.compile(
    r"^\s*(?:public|internal|private|protected)\s+(?:static\s+|async\s+|sealed\s+|override\s+|virtual\s+|partial\s+)*"
    r"(?:[A-Za-z_][\w<>,.?\[\]\s]*\s+)([A-Za-z_]\w*)\s*\(",
    re.MULTILINE,
)
NAMESPACE_RE = re.compile(r"^\s*namespace\s+([\w.]+)", re.MULTILINE)


def generate() -> str:
    rows: list[tuple[str, str, list[str]]] = []
    for source_root in SOURCE_ROOTS:
        for path in sorted(source_root.rglob("*.cs")):
            text = path.read_text(encoding="utf-8")
            namespace = (NAMESPACE_RE.search(text).group(1) if NAMESPACE_RE.search(text) else "")
            types = TYPE_RE.findall(text)
            methods = [name for name in METHOD_RE.findall(text) if name not in {"if", "for", "while", "switch", "catch"}]
            rows.append((path.relative_to(ROOT).as_posix(), namespace + (" :: " + ", ".join(types) if types else ""), methods))

    lines = [
        "# C# migration code map (generated)",
        "",
        "> Generated by `csharp/scripts/generate_csharp_code_map.py`. Do not hand-edit.",
        "",
        f"Files: **{len(rows)}** · declared methods: **{sum(len(row[2]) for row in rows)}**",
        "",
        "| Source | Namespace / types | Declared methods |",
        "|---|---|---|",
    ]
    for path, owner, methods in rows:
        method_text = ", ".join(f"`{name}`" for name in methods) if methods else "—"
        lines.append(f"| `{path}` | {owner or '—'} | {method_text} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"STALE: {OUTPUT.relative_to(ROOT)}")
            return 1
        print("PASS: generated C# code map is current")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"WROTE: {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
